Add eslint linter and husky to force no lint errors on commit
SENG499-team-2/SaaSquatch-HubSpot-integration pull request #63
Opened 2021-07-21 04:34 UTC by tolkamps1

This PR adds `eslint` to our project and `prettier`. It is now required for the linter to pass before you will be able to make a commit. Prettier will remove extra lines breaks, etc. and is more towards formatting. Eslint will warn about console.logs etc. and will automatically fix missing semicolons.

To run eslint: `yarn run lint`
To run prettier `yarn run prettify`

These will automatically be run when you try to make a commit. If they fail, your commit will fail and you will need to fix the linting errors before committing.

This change touched a lot of files because I had to fix a bunch of linting errors in order to commit this. There are still a lot of warnings that show up if you run `yarn run lint`, and it would be a good idea to run this before committing to make sure we are deliberate about what warnings we are adding. Warnings that show up but do not fail the commit include having a type of `any` and `console.log`s. 

The actual files relevant to making this addition are:
- package.json
- .eslintrc.js
- .lintstagedrc.js
- .husky/
- .eslintignore

2021-07-21 05:28 UTC, lucianojd approved these changes
Able to build and run application with the changes. Looks good! I think a linter is a great idea!

2021-07-21 16:49 UTC, davidbishoppp requested changes
Wait until the # of open PRs reduces?

2021-07-21 22:59 UTC, davidbishoppp approved these changes

2021-07-22 01:33 UTC, nicolepeverley approved these changes
Once this is rebased I think you're good to merge thanks for adding 🥇

2021-07-22 04:44 UTC, merged